### ISSUE TITLE
Error from tm.plugins.sentiment Score function 

### ISSUE THREAD

**Issue by ianlokh** [mannau/tm.plugin.sentiment#1]
Hi,

Thanks for the package and the work on sentiment mining! I managed to compile the source on R 3.1.1 on Mac OSX 10.9.5 through R Studio v 0.98.1028

However when I run the following script, I get the error:

Error in score(XYZNews) : could not find function "DMetaData"

> #Get stock time series for selected stock
> getSymbols("AAPL", src="yahoo")
[1] "AAPL"
> chartSeries(AAPL, subset='last 3 months')
> addBBands() ### This plots last 3 months of stock trending chart
> #Get news for the specific stock
> XYZNews = WebCorpus(GoogleFinanceSource("AAPL"))
> text.corpus = score(XYZNews)
Error in score(XYZNews) : could not find function "DMetaData"
> meta(text.corpus)
Error in meta(text.corpus) : object 'text.corpus' not found

Would like your kind help in helping me to troubleshoot this issue?

Thanks so much!
Ian

**Comment by robbig2871** [comment]
Look at:
http://cran.r-project.org/web/packages/tm/news.html

Changes in tm version 0.6
Following functions have been removed:

Author(), DateTimeStamp(), CMetaData(), content_meta(), **DMetaData()**, Description(), Heading(), ID(), Language(), LocalMetaData(), Origin(), prescindMeta(), sFilter() (use meta() instead).

Best regards
robert

**Comment by ianlokh** [comment]
Noted with thanks!

**Comment by mannau** [comment]
sorry for the late fix, should work now. 
Thanks for the bug report!
mario

**Comment by robocop-bob** [comment]
Mario,

Thx. it is vorking perfectly now.

Best regards
