### ISSUE TITLE
Error when no positive/negative words identified

### ISSUE THREAD

**Issue by cmishra** [mannau/tm.plugin.sentiment#3]
When the number of positive and negative terms found in a text is 0, an error is thrown (instead of more appropriately a 0. 

The following code should be modified:
```
function (x, positive = posterms_GI(), negative = negterms_GI()) 
{
    pos <- tm_term_score(x, positive)
    neg <- tm_term_score(x, negative)
    (pos - neg)/(pos + neg)
}
```
potentially to:
```
function (x, positive = posterms_GI(), negative = negterms_GI()) 
{
    pos <- tm_term_score(x, positive)
    neg <- tm_term_score(x, negative)
    if (pos + neg > 0) 
        (pos - neg)/(pos + neg)
    else
        0
}
```

I can fork the repository and submit this edit if that's easier for you. Few other things:
* Maybe this scenario should also be a test case?  
* There may be other scenarios where this should be fixed. I can attempt to find/fix those as well, albeit guidance would be welcome.

**Comment by mannau** [comment]
Hi,
thanks for pointing it out - seems like a bug indeed.
If you ask me like that - fork -> edit -> pull request would be the most
preferred option.
Best,
mario


Am 05/09/15 um 19:53 schrieb Chetan Mishra:

**Comment by cmishra** [comment]
The code change seems simple enough. I only see this issue within 'polarity.TermDocumentMatrix', so I've fixed it there. Anywhere else you think this problem may exist? Do you mind if I list myself as a co-author for the method?

**Comment by mannau** [comment]
Fixed it now using an ifelse (since pos + neg is a vector). Thanks for reporting!
